### ISSUE TITLE
動画タイトルのリンクからニコニコ動画へ遷移できない

### ISSUE THREAD

**Issue by hu-ja-ja** [sevenc-nanashi/kikoune#1]
# 再現方法

1. 任意の動画を再生

2. 赤線で囲われたタイトル(リンク)をクリック
![image](https://github.com/user-attachments/assets/2cf9d5a2-6ec5-41fc-9746-96405471bbd7)

3. 生成されるURLから遷移
![image](https://github.com/user-attachments/assets/f7f100f8-6a2e-45dd-8434-ff6cb761cb85)

4. 動画ページに到達できない
![image](https://github.com/user-attachments/assets/a6c6617f-2819-470d-a9c8-c55e2b40bfb2)

追記
「共有」から生成されたリンクは使用可能

**Comment by sevenc-nanashi** [comment]
22e19a1 にて修正しました。
